baseURL = 'https://docs.yozuk.com/'
languageCode = 'en-us'
title = 'Yozuk'
theme = 'hugo-book'

[params]
BookTheme = 'auto'
BookLogo = 'logo.svg'
BookRepo = 'https://github.com/yozuk/yozuk-docs'

[markup.goldmark.renderer]
unsafe = true